# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    services:
      postgres:
        image: postgres:latest
        
        env:
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: test123
          POSTGRES_PORT: 5432
          POSTGRES_USER: test
        ports:
          - 5432:5432
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        PGPASSWORD: postgres
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g npm
    - run: npm install
    - run: |
        PGPASSWORD=test123 psql -h localhost -U test -d test_db -a -f './db/tables.sql'
    - run: npm run build --if-present
    - run: npm test
    env: 
      DATABASE_URL: postgresql://test:test123@localhost:5432/test_db